# Simple workflow for validating pull request
name: Pull request validation

on:
  # Runs on pushes targeting the default branch
  pull-request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        shell: bash
        uses: actions/checkout@v3
      - uses: ./.github/actions/build-pages
